const trans={
    de:{
        title:"Überschrift",
        changeTheme:"Design wählen",
        main:"Hauptteil",
        footer:"Fußnote",
        page1:"Forschritt der Website",
        page2:"Lebenslauf",
        logIn:"log in",
        signIn:"Profil erstellen",
        gender:"Anrede",
        male:"Herr",
        female:"Frau",
        firstname:"Vorname",
        lastname:"Nachname",
        username:"Benutzername",
        password:"Passwort",
        dateob:"Geburtsdatum",
        submit:"Nutzer speichern",
        loginAlert:"Bitte erste alle Daten ausfüllen!",
        wrongLogIn:"falsche Einlog-Daten",
        signUpAlert:"Bitte erst alle Felder ausfüllen!"
    },
    en:{
        title:"title",
        changeTheme:"change theme",
        main:"mainpart",
        footer:"footer",
        page1:"Construction progress",
        page2:"CV",
        logIn:"log in",
        signIn:"sign in",
        gender:"gender",
        male:"male",
        female:"female",
        firstname:"first Name",
        lastname:"last Name",
        username:"username",
        password:"password",
        dateob:"date of birth",
        submit:"save user",
        loginAlert:"Please fill out all required data!",
        wrongLogIn:"wrong Login Date",
        signUpAlert:"Please fill out the whole form!"
    },
    ke:{
        title:"title",
        changeTheme:"change theme",
        main:"mainpart",
        footer:"footer",
        page1:"Contruction progress",
        page2:"CV",
        logIn:"log in",
        signIn:"sign in",
        gender:"gender",
        male:"male",
        female:"female",
        firstname:"first Name",
        lastname:"last Name",
        username:"username",
        password:"password",
        dateob:"date of birth",
        submit:"save user",
        loginAlert:"Please fill out all required data!",
        wrongLogIn:"wrong Login Date",
        signUpAlert:"Please fill out the whole form!"
    }
}
export default trans