const trans={
    de:{
        title:"Überschrift",
        changeTheme:"Design wählen",
        main:"Hauptteil",
        footer:"Fußnote",
        page1:"Forschritt der Website",
        page2:"Lebenslauf",
        logIn:"log in",
        signIn:"Profil erstellen",
        gender:"Anrede",
        male:"Herr",
        female:"Frau",
        firstname:"Vorname",
        lastname:"Nachname",
        username:"Benutzername",
        password:"Passwort",
        dateob:"Geburtsdatum",
        submit:"Nutzer speichern",
        loginAlert:"Bitte erste alle Daten ausfüllen!",
        wrongLogIn:"falsche Einlog-Daten",
        signUpAlert:"Bitte erst alle Felder ausfüllen!",
        steps:"Status",
        status:"Meilenstein",
        date:"Datum",
        used:"Tools",
        cv:"Lebenslauf erstellt",
        backE:"grundliegende Backendfuntionen",
        mongo:"Mongoo DB erstellt und online",
        frontend:"Basis Frontend",
        tranlations:"Übersetzung English/Deutsch",
        styling:"erstes Styling",
        deploy:"Frontend geht online",
        routes:"Projekte zeigen",
        domain:"Domain zuweisen",
        routing:"Routing verbessern",
        backend:"Backend online bringen",
        response:"Responsivness verbessern",
        api:"Wetter oder Maps integrieren",
        landing:"Landing Page erstellen",
        underConst:"Die Website befindet sich noch in der Entwicklung. Den Fortschritt erfährst Du im Reiter Fortschritt der Website."
    },
    en:{
        title:"title",
        changeTheme:"change theme",
        main:"mainpart",
        footer:"footer",
        page1:"Construction progress",
        page2:"CV",
        logIn:"log in",
        signIn:"sign in",
        gender:"gender",
        male:"male",
        female:"female",
        firstname:"first Name",
        lastname:"last Name",
        username:"username",
        password:"password",
        dateob:"date of birth",
        submit:"save user",
        loginAlert:"Please fill out all required data!",
        wrongLogIn:"wrong Login Date",
        signUpAlert:"Please fill out the whole form!",
        steps:"Status",
        status:"Milestone",
        date:"Date",
        used:"techniques",
        cv:"CV created",
        backE:"basics Backend coded",
        mongo:"Mangoo Database online",
        frontend:"general Frontend structure",
        tranlations:"Translation German/English",
        styling:"general Styling",
        deploy:"Frontend went online",
        routes:"Links to projects",
        domain:"connect to domain",
        routing:"improve Routing",
        backend:"bringing Backend online",
        response:"improve responsivness",
        api:"integrating maps or weather",
        landing:"creating a landing page",
        underConst:"The website is still under construction. The progress you can see under Construction progress."
    },
    ke:{
        title:"title",
        changeTheme:"change theme",
        main:"mainpart",
        footer:"footer",
        page1:"Contruction progress",
        page2:"CV",
        logIn:"log in",
        signIn:"sign in",
        gender:"gender",
        male:"male",
        female:"female",
        firstname:"first Name",
        lastname:"last Name",
        username:"username",
        password:"password",
        dateob:"date of birth",
        submit:"save user",
        loginAlert:"Please fill out all required data!",
        wrongLogIn:"wrong Login Date",
        signUpAlert:"Please fill out the whole form!",
        steps:"Status",
        status:"Milestone",
        date:"Date",
        used:"techniques",
        cv:"CV created",
        backE:"basics Backend coded",
        mongo:"Mangoo Database online",
        frontend:"general Frontend structure",
        tranlations:"Translation German/English",
        styling:"general Styling",
        deploy:"Frontend went online",
        routes:"Links to projects",
        domain:"connect to domain",
        routing:"improve Routing",
        backend:"bringing Backend online",
        response:"improve responsivness",
        api:"integrating maps or weather",
        landing:"creating a landing page",
        underConst:"The website is still under construction. The progress you can see under Construction progress."
    }
}
export default trans